### ISSUE TITLE
OBJC_CLASS_$_PTFWInitialSetupViewControlle not found

### ISSUE THREAD

**Issue by mshoaib1695** [Simicart/react-native-paytabs-sdk#5]
I am getting this error when I run application

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PTFWInitialSetupViewController", referenced from:
      objc-class-ref in libreact-native-paytabs-sdk.a(PaytabsSdk.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I have gone through your documentation for IOS followed it but still there something I may have missed
please help me to resolve this error

**Comment by shashwatsahu** [comment]
Please confirm are you testing in Simulator as it won't work in Simulator, it will only work in real device.

**Comment by aditiproctur** [comment]
I am getting the same error when I run an application on a real device.  Please suggest the solution. @shashwatsahu  @chockwadi 
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PTFWInitialSetupViewController", referenced from:
      objc-class-ref in libreact-native-paytabs-sdk.a(PaytabsSdk.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mshoaib1695** [comment]
I was also not able resolve this issue, and auther is not maintaining the code.
you can use this package https://github.com/paytabscom/react-native-paytabs-library
I think this official package from paytabs and easy to implement. I did the same and It is working fine
